### ISSUE TITLE
Slack invite link expired

### ISSUE THREAD

**Issue by 93Dennis** [webarkit/webarkit.github.io#6]
Hey there, just wanted to tell you that the invite link to your Slack channel doesn't work anymore.
Would you provide a new one, please? :)

**Comment by ThorstenBux** [comment]
Thank you @93Dennis . New link here: https://join.slack.com/t/webarkit/shared_invite/zt-eupovakz-7e2spEifwn~rOHC0vpaWhw

They expire after 30 days I just found

**Comment by kalwalt** [comment]
@93Dennis  you are welcome! @ThorstenBux do you know if it is possible to share a permanent invite link?

**Comment by kalwalt** [comment]
solved with PR #7
